### ISSUE TITLE
Logfile readability

### ISSUE THREAD

**Issue by sroughto** [austincloudguru/ansible-role-splunk-forwarder#7]
It might be helpful to ensure that the splunk user can read the logfiles. For example, we use a separate acl task to ensure the logs are readable by splunk:
```
  - name: Ensure Logs Readable
    acl:
        path: /var/log/messages
        entity: splunk
        state: present
        etype: user
        permissions: r
    become: True
```
